Tidy up code by declaring globals in one place + rename local variable to avoid confusing it with a global variable

diff --git a/x86-64-level b/x86-64-level
--- a/x86-64-level
+++ b/x86-64-level
@@ -43,7 +43,7 @@
 #' $ echo $?
 #' 1
 #'
-#' Version: 0.2.2-9010
+#' Version: 0.2.2-9011
 #' License: CC BY-SA 4.0
 #' Source code: https://github.com/HenrikBengtsson/x86-64-level
 #'
@@ -73,7 +73,12 @@ version() {
 #---------------------------------------------------------------------
 # CPU functions
 #---------------------------------------------------------------------
+## The CPU information read, the CPU flags parsed from it, and the
+## x86-64 level inferred from those flags
 data=
+flags=
+level=0
+
 read_input() {
     if [[ -z ${data} ]]; then
         if ${stdin}; then
@@ -99,19 +104,19 @@ get_cpu_name() {
 
 
 get_cpu_flags() {
-    local flags
-    flags=$(grep "^flags[[:space:]]*:" <<< "${data}" | head -n 1)
-    flags="${flags#*:}"
-    flags="${flags## }"
-    if [[ ! ${flags} =~ [^[:space:]] ]]; then
+    local bfr
+    bfr=$(grep "^flags[[:space:]]*:" <<< "${data}" | head -n 1)
+    bfr="${bfr#*:}"
+    bfr="${bfr## }"
+    if [[ ! ${bfr} =~ [^[:space:]] ]]; then
         echo >&2 "ERROR: No CPU 'flags' entry in the input data"
         exit 1
     fi
-    if grep -v -q -E "^[[:lower:][:digit:]_ ]+$" <<< "${flags}"; then
-        echo >&2 "ERROR: Cannot reliably infer the CPU x86-64 level, because the format of the CPU flags comprise of other symbols than only lower-case letters, digits, and underscores: '${flags}'"
+    if grep -v -q -E "^[[:lower:][:digit:]_ ]+$" <<< "${bfr}"; then
+        echo >&2 "ERROR: Cannot reliably infer the CPU x86-64 level, because the format of the CPU flags comprise of other symbols than only lower-case letters, digits, and underscores: '${bfr}'"
         exit 1
     fi
-    echo "${flags}"
+    echo "${bfr}"
 }
 
 
@@ -120,8 +125,6 @@ validate_cpu_flags() {
     get_cpu_flags > /dev/null
 }
 
-
-flags=""
 
 ## Reports on the identified level, with the CPU name, if known
 explain() {
@@ -154,12 +157,10 @@ has_cpu_flags() {
 }
 
 
-level=0
-
 determine_cpu_version() {
     ## x86-64-v0 (can this happen?)
     level=0
-    
+
     ## x86-64-v1
     has_cpu_flags lm cmov cx8 fpu fxsr mmx syscall sse2 || return 0
     level=1
@@ -167,7 +168,7 @@ determine_cpu_version() {
     ## x86-64-v2
     has_cpu_flags cx16 lahf_lm popcnt sse4_1 sse4_2 ssse3 || return 0
     level=2
-    
+
     ## x86-64-v3
     has_cpu_flags avx avx2 bmi1 bmi2 f16c fma abm movbe xsave || return 0
     level=3
