Add support for x86-64-level --assert=<level>

diff --git a/x86-64-level b/x86-64-level
--- a/x86-64-level
+++ b/x86-64-level
@@ -9,9 +9,11 @@
 #' x86-64-version
 #'
 #' Options:
-#'   --help     Show this help
-#'   --version  Show the version of this tool
-#'   --verbose  Explain the identified level
+#'   --help            Show this help
+#'   --version         Show the version of this tool
+#'   --verbose         Explain the identified level
+#'   --assert=<level>  Assert that CPU supports x86-64-v<level> with
+#'                     exit code 0 is supported, otherwise 1
 #'
 #' Examples:
 #' $ x86-64-level
@@ -29,7 +31,16 @@
 #' $ cat /proc/cpuinfo | x86-64-level -
 #' 3
 #'
-#' Version: 0.1.0-9001
+#' $ x86-64-level --assert=2
+#' $ echo $?
+#' 0
+#'
+#' $ x86-64-level --assert=4
+#' The CPU on this host ('gandalf') supports x86-64-v3, which is less than the required x86-64-v4
+#' $ echo $?
+#' 1
+#'
+#' Version: 0.1.0-9002
 #' License: CC BY-SA 4.0
 #' Source: https://github.com/ucsf-wynton/wynton-tools
 #'
@@ -155,6 +166,7 @@ report_cpu_version() {
 #---------------------------------------------------------------------
 verbose=false
 stdin=false
+assert=
 
 # Parse command-line options
 while [[ $# -gt 0 ]]; do
@@ -169,6 +181,29 @@ while [[ $# -gt 0 ]]; do
         verbose=true
     elif [[ "$1" == "-" ]]; then
         stdin=true
+    elif [[ "$1" == "--assert" ]]; then
+        verbose=true
+    ## Options (--key=value):
+    elif [[ "$1" =~ ^--.*=.*$ ]]; then
+        key=${1//--}
+        key=${key//=*}
+        value=${1//--[[:alpha:]]*=}
+        if [[ -z $value ]]; then
+            merror "Option '--$key' must not be empty"
+        fi
+        if [[ "$key" == "assert" ]]; then
+            assert=$value
+            if [[ ! $assert =~ ^-?[0-9]+$ ]]; then
+                echo >&2 "ERROR: Option --assert does not specify an integer: $assert"
+                exit 2
+            elif [[ $assert -lt 1 ]] || [[ $assert -gt 4 ]]; then
+                echo >&2 "ERROR: Option --assert is out of range [1,4]: $assert"
+                exit 2
+            fi
+        else
+            echo >&2 "ERROR: Unknown option: $1"
+            exit 2
+        fi
     else
         echo >&2 "ERROR: Unknown option: $1"
         exit 2
@@ -177,4 +212,12 @@ while [[ $# -gt 0 ]]; do
 done
 
 
-report_cpu_version
+if [[ -n $assert ]]; then
+    version=$(report_cpu_version)
+    if [[ $version < $assert ]]; then
+        echo "The CPU on this host ('${HOSTNAME}') supports x86-64-v${version}, which is less than the required x86-64-v${assert}"
+        exit 1
+    fi
+else
+    report_cpu_version
+fi
